import { DeviceProperties, Page, Widget } from './types/models';

function propertiesPlaceholder(obj: string): string[] {
  switch (obj) {
    case 'label':
      return ['      "text": \'{{ states("sensor.TODO") }}\''];
    case 'btn':
    case 'button':
      return ['      "enabled": "true"'];
    case 'switch':
    case 'checkbox':
      return ['      "val": \'{{ 0 if is_state("switch.TODO", "off") else 1 }}\''];
    case 'slider':
    case 'arc':
      return ['      "val": \'{{ states("sensor.TODO") | int }}\''];
    case 'gauge':
    case 'bar':
    case 'linemeter':
      return ['      "val": \'{{ states("sensor.TODO") | float }}\''];
    case 'dropdown':
    case 'roller':
      return [
        '      "val": "0"',
        '      # "options": "Option 1\\nOption 2\\nOption 3"',
      ];
    default:
      return ['      # "text": "TODO"'];
  }
}

function eventPlaceholder(obj: string): string[] | null {
  switch (obj) {
    case 'btn':
    case 'button':
      return [
        '      "up":',
        '        - service: TODO.TODO',
        '          target:',
        '            entity_id: TODO.TODO',
      ];
    case 'switch':
      return [
        '      "up":',
        '        - service: switch.toggle',
        '          target:',
        '            entity_id: switch.TODO',
      ];
    case 'checkbox':
      return [
        '      "up":',
        '        - service: TODO.TODO',
        '          target:',
        '            entity_id: TODO.TODO',
      ];
    case 'slider':
    case 'arc':
      return [
        '      "changed":',
        '        - service: TODO.TODO',
        '          target:',
        '            entity_id: TODO.TODO',
        '          data:',
        '            value: "{{ val }}"',
      ];
    case 'dropdown':
    case 'roller':
      return [
        '      "changed":',
        '        - service: TODO.TODO',
        '          target:',
        '            entity_id: TODO.TODO',
        '          data:',
        '            option: "{{ text }}"',
      ];
    default:
      return null;
  }
}

export function generateHAConfig(deviceProperties: DeviceProperties, pages: Page[]): string {
  const { deviceName } = deviceProperties;
  const nodeName = deviceName.toLowerCase().replace(/\s+/g, '_');

  const lines: string[] = [
    `# Configuration for ${deviceName}`,
    `# Generated by openHASP Editor`,
    `#`,
    `# Include in configuration.yaml as:`,
    `#   openhasp:`,
    `#     ${nodeName}: !include openhasp/${nodeName}_config.yaml`,
    `#`,
    `# Replace all TODO placeholders with your actual entity IDs and services.`,
    `objects:`,
  ];

  for (const page of pages) {
    const pageName = page.id === 0 ? 'Overlay (all pages)' : (page.name ?? page.comment ?? `Page ${page.id}`);
    lines.push(`  #####################################`);
    lines.push(`  # Page ${page.id} \u2014 ${pageName}`);
    lines.push(`  #####################################`);

    for (const widget of page.widgets) {
      const addr = `p${page.id}b${widget.id}`;
      const widgetLabel = widget.name ?? widget.description ?? widget.obj;
      lines.push(`  - obj: "${addr}"  # ${widgetLabel}`);

      lines.push(`    properties:`);
      lines.push(...propertiesPlaceholder(widget.obj));

      const events = eventPlaceholder(widget.obj);
      if (events) {
        lines.push(`    event:`);
        lines.push(...events);
      }

      lines.push('');
    }
  }

  return lines.join('\n') + '\n';
}
